# Site settings
title: danielro.se
email: im@danielro.se
description: > # this means to ignore newlines until "baseurl:"
  Daniel Rose, Lead Front End Web Developer at The Genuine Gemstone Company.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://danielro.se" # the base hostname & protocol for your site
twitter_username: danjayrose
github_username:  danjayrose
permalink: /@danjayrose/:title

# Build settings
markdown: kramdown
